"""
RuneScapeExpTracker.py
Shows RuneScape total level, exp, and ranks for each skill
"""

import requests
from tkinter import *


headers = {
    'From': 'email@gmail.com'
}

skills = ["Overall","Attack","Defence","Strength","Constitution","Ranged","Prayer","Magic","Cooking","Woodcutting","Fletching","Fishing","Firemaking","Crafting","Smithing","Mining",
          "Herblore","Agility","Thieving","Slayer","Farming","Runecrafting","Hunter","Construction","Summoning","Dungeoneering","Divination","Invention","Archaeology","Necromancy"]
playerExp = {}
playerLevels = {}
playerRanks = {}

def getCurrentExp(name):
    playerExp.clear()
    playerLevels.clear()
    playerRanks.clear()
    urlString = "https://secure.runescape.com/m=hiscore/index_lite.ws?player=" + name
    response = requests.get(urlString, headers=headers)
    n = 0
    splitResponse = response.text.split("\n")
    for i in skills:
        current = splitResponse[n].split(",")
        playerRanks[i] = current[0]
        playerLevels[i] = current[1]
        playerExp[i] = current[2]
        n+=1


def main():
    
    window = Tk()
    window.title("RuneScapeExpTracker")
    window.geometry('575x1025')
    window.tk.call('tk', 'scaling', 2.0)

    def getInput():
        INPUT = userTextBox.get("1.0","end-1c")
        getCurrentExp(INPUT)
        for i in range(len(rankText)):
            rankText[i].delete(1.0,END)
            rankText[i].insert(END,playerRanks[skills[i]])
            levelText[i].delete(1.0,END)
            levelText[i].insert(END,playerLevels[skills[i]])
            expText[i].delete(1.0,END)
            expText[i].insert(END,playerExp[skills[i]])

    enterNameLbl = Label(window, text="Enter Username: ")
    enterNameLbl.grid(column=1, row=0)
    userTextBox = Text(window, height=1, width=12)
    userTextBox.grid(column=2, row=0)
    getInfoButton = Button(window, height=0, width=10, text="Get Info", command=lambda:getInput())
    getInfoButton.grid(column=3,row=0,padx=5)

    skillLabel = Label(window, text="Skill")
    skillLabel.grid(column=1,row=1)
    rankLabel = Label(window,text="Rank")
    rankLabel.grid(column=2,row=1)
    levelLabel = Label(window, text="Level")
    levelLabel.grid(column=3,row=1)
    expLabel = Label(window, text="Experience")
    expLabel.grid(column=4,row=1)

    rankText = []
    levelText = []
    expText = []

    overall = Label(window,text="Overall: ")
    overall.grid(column=1,row=2,padx=5)
    overallRank = Text(window, height=1, width=12, bg="light cyan")
    overallRank.grid(column=2,row=2,padx=5)
    rankText.append(overallRank)
    overallLevel = Text(window, height=1, width=12, bg="light cyan")
    overallLevel.grid(column=3,row=2,padx=5)
    levelText.append(overallLevel)
    overallExp = Text(window, height=1, width=12, bg="light cyan")
    overallExp.grid(column=4,row=2,padx=5)
    expText.append(overallExp)

    atk = Label(window,text="Attack: ")
    atk.grid(column=1,row=3)
    atkRank = Text(window, height=1, width=12, bg="light cyan")
    atkRank.grid(column=2,row=3)
    rankText.append(atkRank)
    atkLevel = Text(window, height=1, width=12, bg="light cyan")
    atkLevel.grid(column=3,row=3)
    levelText.append(atkLevel)
    atkExp = Text(window, height=1, width=12, bg="light cyan")
    atkExp.grid(column=4,row=3)
    expText.append(atkExp)

    defe = Label(window,text="Defence: ")
    defe.grid(column=1,row=4)
    defRank = Text(window, height=1, width=12, bg="light cyan")
    defRank.grid(column=2,row=4)
    rankText.append(defRank)
    defLevel = Text(window, height=1, width=12, bg="light cyan")
    defLevel.grid(column=3,row=4)
    levelText.append(defLevel)
    defExp = Text(window, height=1, width=12, bg="light cyan")
    defExp.grid(column=4,row=4)
    expText.append(defExp)

    stre = Label(window,text="Strength: ")
    stre.grid(column=1,row=5)
    strRank = Text(window, height=1, width=12, bg="light cyan")
    strRank.grid(column=2,row=5)
    rankText.append(strRank)
    strLevel = Text(window, height=1, width=12, bg="light cyan")
    strLevel.grid(column=3,row=5)
    levelText.append(strLevel)
    strExp = Text(window, height=1, width=12, bg="light cyan")
    strExp.grid(column=4,row=5)
    expText.append(strExp)

    constit = Label(window,text="Constitution: ")
    constit.grid(column=1,row=6)
    constitRank = Text(window, height=1, width=12, bg="light cyan")
    constitRank.grid(column=2,row=6)
    rankText.append(constitRank)
    constitLevel = Text(window, height=1, width=12, bg="light cyan")
    constitLevel.grid(column=3,row=6)
    levelText.append(constitLevel)
    constitExp = Text(window, height=1, width=12, bg="light cyan")
    constitExp.grid(column=4,row=6)
    expText.append(constitExp)

    ranged = Label(window,text="Ranged: ")
    ranged.grid(column=1,row=7)
    rangeRank = Text(window, height=1, width=12, bg="light cyan")
    rangeRank.grid(column=2,row=7)
    rankText.append(rangeRank)
    rangeLevel = Text(window, height=1, width=12, bg="light cyan")
    rangeLevel.grid(column=3,row=7)
    levelText.append(rangeLevel)
    rangeExp = Text(window, height=1, width=12, bg="light cyan")
    rangeExp.grid(column=4,row=7)
    expText.append(rangeExp)

    pray = Label(window,text="Prayer: ")
    pray.grid(column=1,row=8)
    prayRank = Text(window, height=1, width=12, bg="light cyan")
    prayRank.grid(column=2,row=8)
    rankText.append(prayRank)
    prayLevel = Text(window, height=1, width=12, bg="light cyan")
    prayLevel.grid(column=3,row=8)
    levelText.append(prayLevel)
    prayExp = Text(window, height=1, width=12, bg="light cyan")
    prayExp.grid(column=4,row=8)
    expText.append(prayExp)

    mage = Label(window,text="Magic: ")
    mage.grid(column=1,row=9)
    mageRank = Text(window, height=1, width=12, bg="light cyan")
    mageRank.grid(column=2,row=9)
    rankText.append(mageRank)
    mageLevel = Text(window, height=1, width=12, bg="light cyan")
    mageLevel.grid(column=3,row=9)
    levelText.append(mageLevel)
    mageExp = Text(window, height=1, width=12, bg="light cyan")
    mageExp.grid(column=4,row=9)
    expText.append(mageExp)

    cook = Label(window,text="Cooking: ")
    cook.grid(column=1,row=10)
    cookRank = Text(window, height=1, width=12, bg="light cyan")
    cookRank.grid(column=2,row=10)
    rankText.append(cookRank)
    cookLevel = Text(window, height=1, width=12, bg="light cyan")
    cookLevel.grid(column=3,row=10)
    levelText.append(cookLevel)
    cookExp = Text(window, height=1, width=12, bg="light cyan")
    cookExp.grid(column=4,row=10)
    expText.append(cookExp)

    wood = Label(window,text="Woodcutting: ")
    wood.grid(column=1,row=11)
    woodRank = Text(window, height=1, width=12, bg="light cyan")
    woodRank.grid(column=2,row=11)
    rankText.append(woodRank)
    woodLevel = Text(window, height=1, width=12, bg="light cyan")
    woodLevel.grid(column=3,row=11)
    levelText.append(woodLevel)
    woodExp = Text(window, height=1, width=12, bg="light cyan")
    woodExp.grid(column=4,row=11)
    expText.append(woodExp)

    fletch = Label(window,text="Fletching: ")
    fletch.grid(column=1,row=12)
    fletchRank = Text(window, height=1, width=12, bg="light cyan")
    fletchRank.grid(column=2,row=12)
    rankText.append(fletchRank)
    fletchLevel = Text(window, height=1, width=12, bg="light cyan")
    fletchLevel.grid(column=3,row=12)
    levelText.append(fletchLevel)
    fletchExp = Text(window, height=1, width=12, bg="light cyan")
    fletchExp.grid(column=4,row=12)
    expText.append(fletchExp)

    fish = Label(window,text="Fishing: ")
    fish.grid(column=1,row=13)
    fishRank = Text(window, height=1, width=12, bg="light cyan")
    fishRank.grid(column=2,row=13)
    rankText.append(fishRank)
    fishLevel = Text(window, height=1, width=12, bg="light cyan")
    fishLevel.grid(column=3,row=13)
    levelText.append(fishLevel)
    fishExp = Text(window, height=1, width=12, bg="light cyan")
    fishExp.grid(column=4,row=13)
    expText.append(fishExp)

    fire = Label(window,text="Firemaking: ")
    fire.grid(column=1,row=14)
    fireRank = Text(window, height=1, width=12, bg="light cyan")
    fireRank.grid(column=2,row=14)
    rankText.append(fireRank)
    fireLevel = Text(window, height=1, width=12, bg="light cyan")
    fireLevel.grid(column=3,row=14)
    levelText.append(fireLevel)
    fireExp = Text(window, height=1, width=12, bg="light cyan")
    fireExp.grid(column=4,row=14)
    expText.append(fireExp)

    craft = Label(window,text="Crafting: ")
    craft.grid(column=1,row=15)
    craftRank = Text(window, height=1, width=12, bg="light cyan")
    craftRank.grid(column=2,row=15)
    rankText.append(craftRank)
    craftLevel = Text(window, height=1, width=12, bg="light cyan")
    craftLevel.grid(column=3,row=15)
    levelText.append(craftLevel)
    craftExp = Text(window, height=1, width=12, bg="light cyan")
    craftExp.grid(column=4,row=15)
    expText.append(craftExp)

    smith = Label(window,text="Smithing: ")
    smith.grid(column=1,row=16)
    smithRank = Text(window, height=1, width=12, bg="light cyan")
    smithRank.grid(column=2,row=16)
    rankText.append(smithRank)
    smithLevel = Text(window, height=1, width=12, bg="light cyan")
    smithLevel.grid(column=3,row=16)
    levelText.append(smithLevel)
    smithExp = Text(window, height=1, width=12, bg="light cyan")
    smithExp.grid(column=4,row=16)
    expText.append(smithExp)

    mine = Label(window,text="Mining: ")
    mine.grid(column=1,row=17)
    mineRank = Text(window, height=1, width=12, bg="light cyan")
    mineRank.grid(column=2,row=17)
    rankText.append(mineRank)
    mineLevel = Text(window, height=1, width=12, bg="light cyan")
    mineLevel.grid(column=3,row=17)
    levelText.append(mineLevel)
    mineExp = Text(window, height=1, width=12, bg="light cyan")
    mineExp.grid(column=4,row=17)
    expText.append(mineExp)

    herb = Label(window,text="Herblore: ")
    herb.grid(column=1,row=18)
    herbRank = Text(window, height=1, width=12, bg="light cyan")
    herbRank.grid(column=2,row=18)
    rankText.append(herbRank)
    herbLevel = Text(window, height=1, width=12, bg="light cyan")
    herbLevel.grid(column=3,row=18)
    levelText.append(herbLevel)
    herbExp = Text(window, height=1, width=12, bg="light cyan")
    herbExp.grid(column=4,row=18)
    expText.append(herbExp)

    agil = Label(window,text="Agility: ")
    agil.grid(column=1,row=19)
    agilRank = Text(window, height=1, width=12, bg="light cyan")
    agilRank.grid(column=2,row=19)
    rankText.append(agilRank)
    agilLevel = Text(window, height=1, width=12, bg="light cyan")
    agilLevel.grid(column=3,row=19)
    levelText.append(agilLevel)
    agilExp = Text(window, height=1, width=12, bg="light cyan")
    agilExp.grid(column=4,row=19)
    expText.append(agilExp)

    thiev = Label(window,text="Thieving: ")
    thiev.grid(column=1,row=20)
    thievRank = Text(window, height=1, width=12, bg="light cyan")
    thievRank.grid(column=2,row=20)
    rankText.append(thievRank)
    thievLevel = Text(window, height=1, width=12, bg="light cyan")
    thievLevel.grid(column=3,row=20)
    levelText.append(thievLevel)
    thievExp = Text(window, height=1, width=12, bg="light cyan")
    thievExp.grid(column=4,row=20)
    expText.append(thievExp)

    slay = Label(window,text="Slayer: ")
    slay.grid(column=1,row=21)
    slayRank = Text(window, height=1, width=12, bg="light cyan")
    slayRank.grid(column=2,row=21)
    rankText.append(slayRank)
    slayLevel = Text(window, height=1, width=12, bg="light cyan")
    slayLevel.grid(column=3,row=21)
    levelText.append(slayLevel)
    slayExp = Text(window, height=1, width=12, bg="light cyan")
    slayExp.grid(column=4,row=21)
    expText.append(slayExp)

    farm = Label(window,text="Farming: ")
    farm.grid(column=1,row=22)
    farmRank = Text(window, height=1, width=12, bg="light cyan")
    farmRank.grid(column=2,row=22)
    rankText.append(farmRank)
    farmLevel = Text(window, height=1, width=12, bg="light cyan")
    farmLevel.grid(column=3,row=22)
    levelText.append(farmLevel)
    farmExp = Text(window, height=1, width=12, bg="light cyan")
    farmExp.grid(column=4,row=22)
    expText.append(farmExp)

    rune = Label(window,text="Runecrafting: ")
    rune.grid(column=1,row=23)
    runeRank = Text(window, height=1, width=12, bg="light cyan")
    runeRank.grid(column=2,row=23)
    rankText.append(runeRank)
    runeLevel = Text(window, height=1, width=12, bg="light cyan")
    runeLevel.grid(column=3,row=23)
    levelText.append(runeLevel)
    runeExp = Text(window, height=1, width=12, bg="light cyan")
    runeExp.grid(column=4,row=23)
    expText.append(runeExp)

    hunt = Label(window,text="Hunter: ")
    hunt.grid(column=1,row=24)
    huntRank = Text(window, height=1, width=12, bg="light cyan")
    huntRank.grid(column=2,row=24)
    rankText.append(huntRank)
    huntLevel = Text(window, height=1, width=12, bg="light cyan")
    huntLevel.grid(column=3,row=24)
    levelText.append(huntLevel)
    huntExp = Text(window, height=1, width=12, bg="light cyan")
    huntExp.grid(column=4,row=24)
    expText.append(huntExp)

    construct = Label(window,text="Construction: ")
    construct.grid(column=1,row=25)
    constructRank = Text(window, height=1, width=12, bg="light cyan")
    constructRank.grid(column=2,row=25)
    rankText.append(constructRank)
    constructLevel = Text(window, height=1, width=12, bg="light cyan")
    constructLevel.grid(column=3,row=25)
    levelText.append(constructLevel)
    constructExp = Text(window, height=1, width=12, bg="light cyan")
    constructExp.grid(column=4,row=25)
    expText.append(constructExp)

    summ = Label(window,text="Summoning: ")
    summ.grid(column=1,row=26)
    summRank = Text(window, height=1, width=12, bg="light cyan")
    summRank.grid(column=2,row=26)
    rankText.append(summRank)
    summLevel = Text(window, height=1, width=12, bg="light cyan")
    summLevel.grid(column=3,row=26)
    levelText.append(summLevel)
    summExp = Text(window, height=1, width=12, bg="light cyan")
    summExp.grid(column=4,row=26)
    expText.append(summExp)

    dung = Label(window,text="Dungeoneering: ")
    dung.grid(column=1,row=27)
    dungRank = Text(window, height=1, width=12, bg="light cyan")
    dungRank.grid(column=2,row=27)
    rankText.append(dungRank)
    dungLevel = Text(window, height=1, width=12, bg="light cyan")
    dungLevel.grid(column=3,row=27)
    levelText.append(dungLevel)
    dungExp = Text(window, height=1, width=12, bg="light cyan")
    dungExp.grid(column=4,row=27)
    expText.append(dungExp)

    div = Label(window,text="Divination: ")
    div.grid(column=1,row=28)
    divRank = Text(window, height=1, width=12, bg="light cyan")
    divRank.grid(column=2,row=28)
    rankText.append(divRank)
    divLevel = Text(window, height=1, width=12, bg="light cyan")
    divLevel.grid(column=3,row=28)
    levelText.append(divLevel)
    divExp = Text(window, height=1, width=12, bg="light cyan")
    divExp.grid(column=4,row=28)
    expText.append(divExp)

    inv = Label(window,text="Invention: ")
    inv.grid(column=1,row=29)
    invRank = Text(window, height=1, width=12, bg="light cyan")
    invRank.grid(column=2,row=29)
    rankText.append(invRank)
    invLevel = Text(window, height=1, width=12, bg="light cyan")
    invLevel.grid(column=3,row=29)
    levelText.append(invLevel)
    invExp = Text(window, height=1, width=12, bg="light cyan")
    invExp.grid(column=4,row=29)
    expText.append(invExp)

    arch = Label(window,text="Archaeology: ")
    arch.grid(column=1,row=30)
    archRank = Text(window, height=1, width=12, bg="light cyan")
    archRank.grid(column=2,row=30)
    rankText.append(archRank)
    archLevel = Text(window, height=1, width=12, bg="light cyan")
    archLevel.grid(column=3,row=30)
    levelText.append(archLevel)
    archExp = Text(window, height=1, width=12, bg="light cyan")
    archExp.grid(column=4,row=30)
    expText.append(archExp)

    nec = Label(window,text="Necromancy: ")
    nec.grid(column=1,row=31)
    necRank = Text(window, height=1, width=12, bg="light cyan")
    necRank.grid(column=2,row=31)
    rankText.append(necRank)
    necLevel = Text(window, height=1, width=12, bg="light cyan")
    necLevel.grid(column=3,row=31)
    levelText.append(necLevel)
    necExp = Text(window, height=1, width=12, bg="light cyan")
    necExp.grid(column=4,row=31)
    expText.append(necExp)


    window.mainloop()


if __name__ == "__main__":
    main()